### PR TITLE
docs: Clarify usage of event triggers in README

### PR DESCRIPTION
**Pull request by bytestream**
Is the example config currently correct? 

I couldn't get it to work... the only way I got it to work was after looking at https://github.com/amannn/action-semantic-pull-request/blob/master/.github/workflows/lint-pr-title.yml and changing the yml config

### CODE REVIEW

**Comment by amannn** [comment]
Interesting. Can you explain what exactly didn't work?

From how I understand the two events, I think these are the differences:
- `pull_request`: This uses the latest workflow configuration, even if it is potentially changed in the branch. I currently use this in this repository to be able to see changes I make in a given branch, by [referencing the local version of the action](https://github.com/amannn/action-semantic-pull-request/blob/ab9262a21f4c835f52f3069f3353050e836c489d/.github/workflows/lint-pr-title.yml#L17). The downside is, that the action doesn't work when a pull request is created from another repository (that's why the action failed in your PR here).
- `pull_request_target`: This allows the action to be used in a fork-based workflow, where e.g. you want to accept PRs in a public repository. The action and configuration uses the latest configuration from master.

**Comment by bytestream** [comment]
The workflow just didn't start at all. I'd push new commits, edit the title, etc. See https://github.com/proengsoft/laravel-jsvalidation/pull/534

**Comment by amannn** [comment]
Yep, as mentioned above, with `pull_request_target` you'll use the latest configuration from master. As the workflow wasn't in master at that point, there was no check to run.

I think if you have `pull_request_target` configured in master, the workflow will work for the next PR.

If you use `pull_request` (like I have currently configured in this repo), the check won't run for people who make a PR based on a fork (that's why the workflow failed in this PR).

That's at least my current understanding, I'm still wrapping my head around this topic 🙂. If this is correct, I think it should be documented in the README of this action.

**Comment by bytestream** [comment]
Me too! OK thanks for clarifying. I'll try another PR with suggested change

**Comment by bytestream** [comment]
> with pull_request_target you'll use the latest configuration from master. As the workflow wasn't in master at that point, there was no check to run.

This seems like it was the issue. Thanks for the pointer.

Should I update this PR with a little note about it? If you have any suggestions on the wording I'd be grateful.

**Comment by amannn** [comment]
@bytestream I've added a commit with a proposal for the improved README. Would you like to have a look and let me know if there's something to improve?

**Comment by bytestream** [comment]
Thanks. Looks good 👍

**Comment by amannn** [comment]
Great, thanks for your help!

**Pull request merged**
