### PR TITLE
docs: Update Github to GitHub

### PR DESCRIPTION
**Pull request by nicolenumrich**
Nicole from GitHub here! We're big fans of your action and would love to share on our social channels for others to use, but we selfishly also love see GitHub with a capital 'H" 😄  

(I think it's lower case in the About as well 🙃 )

### CODE REVIEW

**Comment by amannn** [comment]
Hi @nicolenumrich! Thank you so much for the PR, I feel flattered 😁. I've just changed the wording in the about section of the repo!

**Comment by amannn** [comment]
@nicolenumrich The action is finally displayed with the correct spelling on GitHub Marketplace in case you still want to share it! 🙂.

**Comment by nicolenumrich** [comment]
> @nicolenumrich The action is finally displayed with the correct spelling on GitHub Marketplace in case you still want to share it! 🙂.

Fantastic! We were actually planning to share later this week or next on our social channels. I'll be sure to share the links when they're up. 🎉

**Comment by nicolenumrich** [comment]
Hi @amannn - we shared your action this morning ([Twitter](https://twitter.com/github/status/1516796840544505857), [LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6922562530242441216)). Thanks so much for creating it and letting us share with our users! ❤️

**Pull request merged**
