### PR TITLE
feat: Ability to add a custom config 🐛

### LINKED ISSUE #39: Support custom tags
I've arrived to this repo from: https://github.com/zeke/semantic-pull-requests

As we are using GHE maybe we cannot use an app, but action looks great.

But, we use some tags that are not the ones defined on this action: `Feature`, `Fix`, Tech`...

Is possible to add the ability to allow tag customization?

Captura de pantalla 2020-10-01 a las 10 24 22

### PR DESCRIPTION
**Pull request by mrchief**
Fixes #39 

Also allows to add more options in future.

### CODE REVIEW

**Comment by mrchief** [comment]
The actual changes are in 4 files. Rest of the files are due to deletion of `node_modules`. Usually `node_modules` are not checked in so I think it was accidentally done so.

**Comment by mrchief** [comment]
Tests are failing as there's no `yarn install` during tests. So because I removed `node_modules`, tests are failing now. I pushed a fix for `test.yml` to do `yarn install` so once you merge this to master, it should go away.

**Comment by alorma** [comment]
you could run a `git rm -r node_modules` to avoid pushing those files

**Comment by mrchief** [comment]
> you could run a `git rm -r node_modules` to avoid pushing those files

Yes - and that's what shows up in the diff - all of the 900+ files are now removed.

**Comment by amannn** [comment]
Hey @mrchief,

thanks a lot for your PR here!

> Usually node_modules are not checked in so I think it was accidentally done so.

For Github Actions it's sadly required, except for if you compile the JavaScript to a binary. See https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github.

I think for now I'd like to stay with simple string arguments and don't use a separate config file. Generally I want to keep configuration to a minimum, so hopefully we don't need more customization soon.

There were some issues with testing changes to the Github Action if the branch is not from an owner. Therefore I created another PR with the relevant changes from your branch here and another one which was opened to solve the same issue: https://github.com/amannn/action-semantic-pull-request/pull/53.

Would you like to help review that branch and provide feedback? Thanks!

**Comment by mrchief** [comment]
> I think for now I'd like to stay with simple string arguments and don't use a separate config file. Generally I want to keep configuration to a minimum, so hopefully we don't need more customization soon.

I thought about this long and hard and usually I prefer the simpler approach. However, in case of semantic commits and conventional changelog, there's no one size fits all scenario. There's ton of customizations one can do via conventional-changelog alone. So the idea with a custom config is to introduce an config API that allows for more changes in the future. Having a string now and adding a file later also work but is bumpy transition IMHO.

Your PR may look clean now but if you decide to support more customizability, then it'd get uglier later. 

That said, it's your project so you're the boss! I can only make suggestions based on experience working with conventional commits for many years now.

If you do decide to go ahead with 53, I'll close this. And If I was able to convince you, then I can undo the node_modules removal here and we can proceed. :)

**Comment by amannn** [comment]
@mrchief Thank you for your thoughtful comment.

> There's ton of customizations one can do via conventional-changelog alone.

Is there an option related to this Github action that you're currently missing?

> Having a string now and adding a file later also work but is bumpy transition IMHO.

I have to say what I dislike a bit about the Github action arguments approach is that only strings are allowed. I think as long as only primitives like strings or booleans are passed, it might be ok, but the array we currently need is where it gets to a maximum.

However I think the upside is that it makes configuration easier. E.g. a CLI might provide defaults, allowing you to override them via arguments but if you really have to configure a lot, you can go for a config file. E.g. [jest has a string option that accepts an array of strings](https://jestjs.io/docs/en/cli#--testpathignorepatternsarray). I think that's a quite natural transition and something that might make sense for this repo as well. In that case once we need a config, your code from this PR will definitely come in handy.

There's a Probot app that is really similar to this Github action: https://github.com/zeke/semantic-pull-requests. Their config currently only consists of strings, booleans and arrays of strings. Given that the project is three years old, I think there might be a chance that the simple argument approach could work for this repository.

What do you think?

Btw. I just saw that [other Github actions](https://github.com/softprops/action-gh-release#%EF%B8%8F-uploading-release-assets) also use string arrays like this:

```
        with:
          files: |
            Release.txt
            LICENSE
```

That could be another option to support arrays of strings.

**Comment by mrchief** [comment]
> Is there an option related to this Github action that you're currently missing?

Glad you asked! I'll give you a couple of use cases:

 - not using angular conventions
 - adding/extending custom conventions. E.g., one could add a rule that every PR title needs to have a JIRA ticket or something else in their title - you can then do this by modifying `headerPattern` & `headerCorrespondence` to ensure that the titles are parsed properly and then post parsing, you get a property that allows you to validate those additional info. 
 - adding more types is another one which we're already discussing in the PR
 - you want to honor/integrate commitlint or a different commitzen config

You mentioned zeke/semantic-pull-requests and I currently use it for some of my simpler setups and if you check its issues, you'll see a lot of feature requests similar to above use cases.

When I said a bumpy transition I was referring to how you pass those arguments - like right now you're using simple arguments but then later, should you happen to support it, you now need to migrate those setting to a file and then specify the file path with GH arguments. May or may not be a big deal but what the current approach gives is say someone has an existing semantic.yml config or a commitlintrc or a conventional config, then they can easily bring it in and start using your PR. Like I and I'm sure there are others who would love to see the ability to support same options that zeke/semantic-pull-requests currently supports.

**Comment by amannn** [comment]
Thanks for your feedback!

Not using angular conventions and adding more types would both be covered with the configurable types, is that correct?

`headerPattern` and `headerCorrespondence` look interesting and so is integrating with tools like `commitlint` or `semantic.yml`. I'm wondering if for these it could make sense to auto-detect an existing config in the repo and use that, so that the user doesn't have to add a separate config with the same content. If we don't do that, I guess we could handle this with string arguments as well though.

@alorma was asking yesterday about the current state for supporting custom types, so I'll merge #53 for now – I hope that's ok for you. If there are further options you need in a project of yours, maybe we can move the discussion to an issue to discuss if they should be new options or if we should auto-detect configuration from other tools to avoid duplicate config.

**Pull request closed without merging**
